# Generated by Django 5.2.14 on 2026-05-13 19:35

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encrypted_payload",
                    encrypted_fields.fields.EncryptedJSONField(default=dict),
                ),
                ("emails_analyzed", models.PositiveIntegerField(default=0)),
                ("last_refreshed_at", models.DateTimeField()),
                ("up_to_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_summaries",
                        to="accounts.firm",
                    ),
                ),
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="emails.emailthread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["firm"], name="summaries_e_firm_id_1d2a0d_idx"
                    ),
                    models.Index(
                        fields=["last_refreshed_at"],
                        name="summaries_e_last_re_08cd6e_idx",
                    ),
                ],
            },
        ),
    ]
