# Generated by Django 5.2.14 on 2026-05-13 19:33

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encrypted_subject",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, default="", max_length=998
                    ),
                ),
                ("external_thread_id", models.CharField(max_length=255, unique=True)),
                ("first_message_at", models.DateTimeField()),
                ("last_message_at", models.DateTimeField()),
                ("up_to_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="clients.client",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_threads",
                        to="accounts.firm",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_message_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_message_id", models.CharField(max_length=255, unique=True)),
                ("sender_email", models.EmailField(max_length=254)),
                ("recipients", models.JSONField(default=dict)),
                (
                    "encrypted_body",
                    encrypted_fields.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("sent_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="clients.client",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_messages",
                        to="accounts.firm",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="emails.emailthread",
                    ),
                ),
            ],
            options={
                "ordering": ("sent_at",),
            },
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["client", "-last_message_at"],
                name="emails_emai_client__b7d717_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(fields=["firm"], name="emails_emai_firm_id_925393_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["thread", "sent_at"], name="emails_emai_thread__cac034_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(fields=["firm"], name="emails_emai_firm_id_1bebaa_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["client"], name="emails_emai_client__b79791_idx"
            ),
        ),
    ]
